name = "RoadRunnerJulia"
uuid = "2e139b0f-e59d-4fae-b5dc-733d9b7ae015"
authors = ["Luke Zhu"]
version = "0.1.0"

[deps]
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
